### PR TITLE
Add `package.json` file

### PR DESCRIPTION
**Pull request by TooTallNate**
I've already published v0.1.2 to npm, and added `mattmueller` as an owner: https://www.npmjs.org/package/word-at-caret

### CODE REVIEW

**Comment by TooTallNate** [comment]
@MatthewMueller ping!

**Comment by MatthewMueller** [comment]
ah wtf, totally missed this. sorry about that!

**Comment by matthewmueller** [comment]
added you and coreh to the repo

**Comment by TooTallNate** [comment]
@MatthewMueller Thanks bro!

**Pull request merged**
